'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=$('map'), canvas=$('mapCanvas'), ctx=canvas.getContext('2d');
const state={stops:[],routes:[],filter:'regular',search:'',selectedRoute:null,selectedStop:null,center:[1.855,50.947],zoom:13,point:null,radius:500,picking:false,tab:'explore',ready:false};
let width=1,height=1,frame=0,tileErrors=0,toastTimer,drag=null,pointers=new Map(),pinch=null,tileCache=new Map();
const nf=new Intl.NumberFormat('fr-FR'), norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const metres=m=>m<1000?nf.format(Math.round(m))+' m':(m/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})+' km';
const badge=r=>`<span class="route-badge" style="--route:${esc(r.color)};--route-text:${esc(r.textColor)}">${esc(r.short)}</span>`;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5200);}
function selectedRoutes(){return state.selectedRoute?[state.selectedRoute]:state.routes.filter(r=>state.filter==='all'||(state.filter==='regular'?r.regular:!r.regular));}
function routeStops(route){if(!route.nearStops){const b=route.bounds;route.nearStops=state.stops.filter(s=>s.coord[0]>=b[0]-.001&&s.coord[0]<=b[2]+.001&&s.coord[1]>=b[1]-.001&&s.coord[1]<=b[3]+.001&&Geo.lineDistance(s.coord,route.lines)<=60).sort((a,b)=>a.name.localeCompare(b.name,'fr'));}return route.nearStops;}
function nearbyRoutes(stop){return state.routes.filter(r=>{const b=r.bounds;return stop.coord[0]>=b[0]-.001&&stop.coord[0]<=b[2]+.001&&stop.coord[1]>=b[1]-.001&&stop.coord[1]<=b[3]+.001&&Geo.lineDistance(stop.coord,r.lines)<=60;});}
function schedule(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;renderMap();});}
function resize(){const b=map.getBoundingClientRect();width=b.width;height=b.height;const d=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(width*d);canvas.height=Math.round(height*d);ctx.setTransform(d,0,0,d,0,0);schedule();}
new ResizeObserver(resize).observe(map);
function screen(coord){const p=Geo.project(coord,state.zoom),c=Geo.project(state.center,state.zoom);return [p[0]-c[0]+width/2,p[1]-c[1]+height/2];}
function coordinate(x,y){const c=Geo.project(state.center,state.zoom);return Geo.unproject([c[0]+x-width/2,c[1]+y-height/2],state.zoom);}
function renderTiles(){if(!$('showBase').checked){$('tiles').hidden=true;$('mapFallback').hidden=true;return;}$('tiles').hidden=false;const c=Geo.project(state.center,state.zoom),left=c[0]-width/2,top=c[1]-height/2,needed=new Set();let tiles=[];const n=2**state.zoom;for(let x=Math.floor(left/256);x<=Math.floor((left+width)/256);x++){for(let y=Math.floor(top/256);y<=Math.floor((top+height)/256);y++){if(y<0||y>=n)continue;const key=`${state.zoom}/${x}/${y}`;needed.add(key);let tile=tileCache.get(key);if(!tile){tile=document.createElement('img');tile.alt='';tile.draggable=false;tile.loading='eager';tile.decoding='async';tile.referrerPolicy='strict-origin-when-cross-origin';tile.src=`https://tile.openstreetmap.org/${state.zoom}/${((x%n)+n)%n}/${y}.png`;tile.onerror=()=>{tile.style.opacity=0;tileErrors++;if(tileErrors>3)$('mapFallback').hidden=false;};tile.onload=()=>{if(tileErrors===0)$('mapFallback').hidden=true;};tileCache.set(key,tile);$('tiles').appendChild(tile);}tile.style.transform=`translate(${Math.round(x*256-left)}px,${Math.round(y*256-top)}px)`;tiles.push(tile);}}
for(const [key,tile]of tileCache)if(!needed.has(key)){tile.remove();tileCache.delete(key);}}
function renderMap(){ctx.clearRect(0,0,width,height);renderTiles();const c=Geo.project(state.center,state.zoom),offset=[width/2-c[0],height/2-c[1]];ctx.strokeStyle='#9abcb418';ctx.lineWidth=1;for(let x=offset[0]%128;x<width;x+=128){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let y=offset[1]%128;y<height;y+=128){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}
const routes=selectedRoutes();if($('showLines').checked){for(const r of routes){ctx.beginPath();for(const line of r.lines){let first=true;for(const p of line){const a=Geo.project(p,state.zoom);if(first){ctx.moveTo(a[0]+offset[0],a[1]+offset[1]);first=false;}else ctx.lineTo(a[0]+offset[0],a[1]+offset[1]);}}ctx.lineJoin='round';ctx.lineCap='round';ctx.globalAlpha=state.selectedRoute?1:.72;ctx.strokeStyle='#ffffff';ctx.lineWidth=state.selectedRoute?7:4.6;ctx.stroke();ctx.strokeStyle=r.color;ctx.lineWidth=state.selectedRoute?4.5:2.5;ctx.stroke();}ctx.globalAlpha=1;}
if(state.point){const p=screen(state.point),metersPerPixel=156543.03392*Math.cos(state.point[1]*Math.PI/180)/2**state.zoom,rad=state.radius/metersPerPixel;ctx.beginPath();ctx.arc(p[0],p[1],rad,0,Math.PI*2);ctx.fillStyle='#087f731b';ctx.fill();ctx.strokeStyle='#087f73';ctx.lineWidth=2;ctx.setLineDash([6,5]);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(p[0],p[1],8,0,Math.PI*2);ctx.fillStyle='#087f73';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();}
const related=state.selectedRoute?new Set(routeStops(state.selectedRoute).map(s=>s.id)):null;let labels=[];if($('showStops').checked){for(const s of state.stops){const p=screen(s.coord);if(p[0]<-10||p[0]>width+10||p[1]<-10||p[1]>height+10)continue;const near=state.point&&Geo.distance(state.point,s.coord)<=state.radius,selected=state.selectedStop===s,isRelated=related&&related.has(s.id);ctx.globalAlpha=related&&!isRelated&&!selected?.28:1;ctx.beginPath();ctx.arc(p[0],p[1],selected?7:near?4.5:state.zoom>=15?3.6:2.8,0,Math.PI*2);ctx.fillStyle=selected||near?'#087f73':'#fff';ctx.fill();ctx.lineWidth=selected?3:1.3;ctx.strokeStyle=selected?'#fff':near?'#fff':isRelated?state.selectedRoute.color:'#4c7880';ctx.stroke();if(selected){ctx.beginPath();ctx.arc(p[0],p[1],11,0,Math.PI*2);ctx.strokeStyle='#087f73';ctx.lineWidth=1.5;ctx.stroke();}ctx.globalAlpha=1;if((state.zoom>=16&&!related)||selected||state.zoom>=15&&isRelated)labels.push({s,p,selected});}}
const used=[];ctx.font='600 11px system-ui';for(const {s,p,selected}of labels.sort((a,b)=>Number(b.selected)-Number(a.selected))){const text=s.name.toLocaleLowerCase('fr').replace(/(^|\s)\S/g,t=>t.toUpperCase()),w=ctx.measureText(text).width,x=p[0]+9,y=p[1]-6;const b=[x-3,y-12,w+6,17];if(!selected&&used.some(a=>b[0]<a[0]+a[2]&&b[0]+b[2]>a[0]&&b[1]<a[1]+a[3]&&b[1]+b[3]>a[1]))continue;used.push(b);ctx.fillStyle='#ffffffea';ctx.fillRect(...b);ctx.fillStyle='#24434b';ctx.fillText(text,x,y);}
const mpp=156543.03392*Math.cos(state.center[1]*Math.PI/180)/2**state.zoom,target=90*mpp,scale=[10,20,50,100,200,500,1000,2000,5000,10000,20000,50000].reduce((prev,n)=>Math.abs(n-target)<Math.abs(prev-target)?n:prev,1000);$('scale').textContent=metres(scale);$('scale').style.width=Math.max(30,scale/mpp)+'px';
}
function updateStatus(){const n=selectedRoutes().length;$('mapStatus').textContent=state.picking?'Cliquez sur la carte pour définir votre point':state.selectedRoute?`Ligne ${state.selectedRoute.short} · ${routeStops(state.selectedRoute).length} arrêts candidats à proximité du tracé`:`${nf.format(n)} lignes affichées · ${nf.format(state.stops.length)} points d’arrêt`;$('mapTitle').textContent=state.selectedRoute?state.selectedRoute.name:'Calais, en mouvement.';}
function renderResults(){if(!state.ready)return;const q=norm(state.search),routes=state.routes.filter(r=>(state.filter==='all'||(state.filter==='regular'?r.regular:!r.regular))&&(!q||norm(r.short+' '+r.name).includes(q)));const stops=q?state.stops.filter(s=>norm(s.name+' '+s.code).includes(q)):[];$('listTitle').textContent=q?'Résultats de recherche':'Les lignes du réseau';$('resultCount').textContent=routes.length+stops.length;
let html=routes.map(r=>`<button class="route-row ${state.selectedRoute===r?'selected':''}" data-route="${esc(r.id)}">${badge(r)}<span class="row-content"><strong>${esc(r.name)}</strong><small>${r.regular?'Ligne régulière':'Autre ligne'} · ${metres(r.length)} de tracé</small></span><span class="row-end" aria-hidden="true">⌁</span></button>`).join('');if(stops.length)html+=`<div class="result-heading"><h2>Arrêts</h2><span class="count">${stops.length}</span></div>`+stops.map(s=>`<button class="stop-row ${state.selectedStop===s?'selected':''}" data-stop="${esc(s.id)}"><span class="row-dot"></span><span class="row-content"><strong>${esc(s.name)}</strong><small>${esc(s.code||'Point d’arrêt')}</small></span><span class="row-end" aria-hidden="true">⌖</span></button>`).join('');$('results').innerHTML=html||'<div class="empty-state">Aucun résultat.<br><span>Essayez un autre nom ou la catégorie « Toutes ».</span></div>';}
function fit(bounds){const [west,south,east,north]=bounds;for(let z=17;z>=8;z--){const a=Geo.project([west,north],z),b=Geo.project([east,south],z);if(b[0]-a[0]<width-110&&b[1]-a[1]<height-200){state.zoom=z;state.center=Geo.unproject([(a[0]+b[0])/2,(a[1]+b[1])/2],z);break;}}schedule();}
function selectRoute(id){const r=state.routes.find(r=>r.id===id);if(!r)return;state.selectedRoute=r;state.selectedStop=null;state.picking=false;map.classList.remove('picking');const stops=routeStops(r);fit(r.bounds);$('detail').hidden=false;$('detail').innerHTML=`<button class="close" data-close aria-label="Fermer la fiche">×</button><div class="eyebrow">EXPLORER UNE LIGNE</div><div style="margin-top:18px">${badge(r)}</div><h3>${esc(r.name)}</h3><p>${r.regular?'Ligne régulière':'Autre ligne du réseau'} · tracé géographique</p><div class="detail-stats"><div><strong>${metres(r.length)}</strong><span>longueur du tracé fourni</span></div><div><strong>${stops.length}</strong><span>arrêts candidats</span></div></div><h4>Arrêts à proximité du tracé</h4><p class="small-note">À moins de 60 m. Desserte non confirmée ; liste alphabétique.</p><div class="detail-stops">${stops.slice(0,15).map(s=>`<button class="detail-stop" data-stop="${esc(s.id)}">${esc(s.name)}</button>`).join('')||'<p>Aucun arrêt à moins de 60 m.</p>'}</div>${stops.length>15?`<p class="small-note">${stops.length-15} autres points proches du tracé.</p>`:''}<button class="btn outline" data-export="${esc(r.id)}">Télécharger ce tracé · GeoJSON</button>`;renderResults();updateStatus();schedule();}
function selectStop(id){const s=state.stops.find(s=>s.id===id);if(!s)return;state.selectedStop=s;state.center=s.coord.slice();state.zoom=Math.max(state.zoom,16);const routes=nearbyRoutes(s);$('detail').hidden=false;$('detail').innerHTML=`<button class="close" data-close aria-label="Fermer la fiche">×</button><div class="eyebrow">POINT D’ARRÊT</div><h3>${esc(s.name)}</h3><p>Code : ${esc(s.code||'Non renseigné')}</p><div class="detail-stats"><div><strong>${routes.length}</strong><span>tracés à moins de 60 m</span></div><div><strong>⌖</strong><span>Coordonnées WGS84</span></div></div><p>${s.coord[1].toFixed(6)}° N · ${s.coord[0].toFixed(6)}° E</p><h4>Tracés à proximité</h4><div class="badge-list">${routes.map(r=>`<button class="route-badge" data-route="${esc(r.id)}" style="--route:${esc(r.color)};--route-text:${esc(r.textColor)}" aria-label="Explorer ${esc(r.name)}">${esc(r.short)}</button>`).join('')||'<p>Aucun tracé proche.</p>'}</div><p class="small-note">Association géographique, sans garantie de desserte.</p><h4>Accessibilité</h4><p>${s.access==='1'?'Accessibilité fauteuil indiquée dans la source.':s.access==='2'?'Non accessible selon la source.':'Information non renseignée dans la source.'}</p><button class="btn primary" data-near-stop="${esc(s.id)}">Explorer autour de cet arrêt</button>`;renderResults();schedule();}
function closeDetail(){state.selectedStop=null;state.selectedRoute=null;$('detail').hidden=true;renderResults();updateStatus();schedule();}
function switchTab(tab){state.tab=tab;for(const t of ['explore','near']){$(t+'Panel').hidden=t!==tab;$(t+'Tab').classList.toggle('active',t===tab);$(t+'Tab').setAttribute('aria-selected',t===tab);$(t+'Tab').tabIndex=t===tab?0:-1;}if(tab==='explore'){state.picking=false;map.classList.remove('picking');updateStatus();}}
function setPoint(coord){state.point=coord.slice();state.center=coord.slice();state.zoom=state.radius<=500?16:14;state.picking=false;state.selectedRoute=null;state.selectedStop=null;map.classList.remove('picking');$('detail').hidden=true;switchTab('near');renderNear();renderResults();updateStatus();schedule();}
function renderNear(){if(!state.point)return;const list=state.stops.map(s=>({s,d:Geo.distance(state.point,s.coord)})).filter(o=>o.d<=state.radius).sort((a,b)=>a.d-b.d);$('nearNote').textContent=`${list.length} point${list.length>1?'s':''} d’arrêt dans un rayon de ${metres(state.radius)}. Distances à vol d’oiseau.`;$('nearResults').innerHTML=list.length?list.map(({s,d})=>`<button class="stop-row" data-stop="${esc(s.id)}"><span class="row-dot"></span><span class="row-content"><strong>${esc(s.name)}</strong><small>${esc(s.code||'Point d’arrêt')}</small></span><strong style="margin-left:auto;font-size:13px;white-space:nowrap;color:var(--accent)">${metres(d)}</strong></button>`).join(''):'<div class="empty-state">Aucun arrêt dans ce rayon.<br><span>Élargissez le rayon ou choisissez un autre point.</span></div>';}
function locate(){if(!state.ready)return;switchTab('near');if(!navigator.geolocation){toast('La localisation n’est pas disponible. Choisissez un point sur la carte.');return;}$('locateButton').disabled=true;$('locateButton').textContent='Recherche de votre position…';navigator.geolocation.getCurrentPosition(p=>{resetLocate();setPoint([p.coords.longitude,p.coords.latitude]);toast('Position trouvée. Précision estimée : '+metres(p.coords.accuracy));},()=>{resetLocate();toast('Position indisponible ou autorisation refusée. Choisissez un point sur la carte.');},{enableHighAccuracy:true,timeout:12000,maximumAge:60000});}
function resetLocate(){$('locateButton').disabled=false;$('locateButton').innerHTML='<span>◎</span> Utiliser ma position';}
function zoom(delta,x=width/2,y=height/2){const next=Math.max(8,Math.min(18,state.zoom+delta));if(next===state.zoom)return;const anchor=coordinate(x,y);state.zoom=next;const p=Geo.project(anchor,next);state.center=Geo.unproject([p[0]-x+width/2,p[1]-y+height/2],next);schedule();}
function mapClick(x,y){if(!state.ready)return;if(state.picking){setPoint(coordinate(x,y));return;}let nearest=null,best=16;if($('showStops').checked)for(const s of state.stops){const p=screen(s.coord),d=Math.hypot(p[0]-x,p[1]-y);if(d<best){best=d;nearest=s;}}if(nearest){selectStop(nearest.id);return;}if($('showLines').checked){const p=coordinate(x,y),limit=156543.03392*Math.cos(p[1]*Math.PI/180)/2**state.zoom*9;let route=null,min=limit;for(const r of selectedRoutes()){const d=Geo.lineDistance(p,r.lines);if(d<min){route=r;min=d;}}if(route)selectRoute(route.id);}}
map.addEventListener('pointerdown',e=>{if(e.button!==0)return;const b=map.getBoundingClientRect();pointers.set(e.pointerId,[e.clientX-b.left,e.clientY-b.top]);map.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,center:Geo.project(state.center,state.zoom),moved:false,id:e.pointerId};if(pointers.size===2){const a=[...pointers.values()];pinch={distance:Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1])};}map.classList.add('dragging');});
map.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const b=map.getBoundingClientRect();pointers.set(e.pointerId,[e.clientX-b.left,e.clientY-b.top]);if(pointers.size===2&&pinch){if(drag)drag.moved=true;const a=[...pointers.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]),ratio=d/pinch.distance;if(ratio>1.7||ratio<.6){zoom(ratio>1?1:-1,(a[0][0]+a[1][0])/2,(a[0][1]+a[1][1])/2);pinch.distance=d;}return;}if(!drag||drag.id!==e.pointerId||pinch)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;state.center=Geo.unproject([drag.center[0]-dx,drag.center[1]-dy],state.zoom);schedule();});
map.addEventListener('pointerup',e=>{const wasPinch=!!pinch;const click=drag&&!drag.moved&&!wasPinch;pointers.delete(e.pointerId);if(pointers.size===0){if(click){const b=map.getBoundingClientRect();mapClick(e.clientX-b.left,e.clientY-b.top);}drag=null;pinch=null;map.classList.remove('dragging');}else if(pointers.size===1){const [id,p]=[...pointers][0];const b=map.getBoundingClientRect();drag={id,x:p[0]+b.left,y:p[1]+b.top,center:Geo.project(state.center,state.zoom),moved:true};pinch=null;}});
map.addEventListener('pointercancel',()=>{pointers.clear();drag=null;pinch=null;map.classList.remove('dragging');});
let wheelAt=0;map.addEventListener('wheel',e=>{e.preventDefault();if(Date.now()-wheelAt<180)return;wheelAt=Date.now();const b=map.getBoundingClientRect();zoom(e.deltaY<0?1:-1,e.clientX-b.left,e.clientY-b.top);},{passive:false});
map.addEventListener('keydown',e=>{if(e.key==='Enter'&&state.picking){e.preventDefault();setPoint(state.center);}else if(['+','=','-'].includes(e.key)){e.preventDefault();zoom(e.key==='-'?-1:1);}else if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const c=Geo.project(state.center,state.zoom),d={ArrowUp:[0,-80],ArrowDown:[0,80],ArrowLeft:[-80,0],ArrowRight:[80,0]}[e.key];state.center=Geo.unproject([c[0]+d[0],c[1]+d[1]],state.zoom);schedule();}});
$('zoomIn').onclick=()=>zoom(1);$('zoomOut').onclick=()=>zoom(-1);$('resetButton').onclick=()=>{closeDetail();state.center=[1.855,50.947];state.zoom=width<500?12:13;state.point=null;state.picking=false;map.classList.remove('picking');$('nearResults').innerHTML='<div class="empty-state">Un point de départ suffit.<br><span>Vos arrêts proches apparaîtront ici.</span></div>';$('nearNote').textContent='Les distances sont calculées à vol d’oiseau.';updateStatus();schedule();};
$('searchInput').oninput=e=>{state.search=e.target.value;renderResults();};
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{state.filter=button.dataset.filter;state.selectedRoute=null;state.selectedStop=null;$('detail').hidden=true;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button);});renderResults();updateStatus();schedule();});
$('exploreTab').onclick=()=>switchTab('explore');$('nearTab').onclick=()=>switchTab('near');document.querySelector('.tabs').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tab=e.key==='Home'?'explore':e.key==='End'?'near':state.tab==='near'?'explore':'near';switchTab(tab);$(tab+'Tab').focus();}});
$('locateButton').onclick=locate;$('mapLocate').onclick=locate;$('choosePointButton').onclick=()=>{if(!state.ready)return;state.picking=true;map.classList.add('picking');updateStatus();map.focus();if(window.innerWidth<741)map.scrollIntoView({behavior:'smooth',block:'center'});toast('Cliquez sur un point, ou déplacez la carte avec les flèches puis appuyez sur Entrée.');};
$('radius').oninput=e=>{state.radius=Number(e.target.value);$('radiusValue').textContent=metres(state.radius);renderNear();schedule();};
$('layersButton').onclick=()=>{const open=$('layersPanel').hidden;$('layersPanel').hidden=!open;$('layersButton').setAttribute('aria-expanded',open);};for(const id of ['showStops','showLines','showBase'])$(id).onchange=schedule;
for(const id of ['aboutButton','dataButton'])$(id).onclick=()=>$('aboutDialog').showModal();$('closeDialog').onclick=()=>$('aboutDialog').close();$('aboutDialog').onclick=e=>{if(e.target===$('aboutDialog')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.target.close();}};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('aboutDialog').open){e.preventDefault();switchTab('explore');$('searchInput').focus();}if(e.key==='Escape'&&!$('aboutDialog').open){state.picking=false;map.classList.remove('picking');$('layersPanel').hidden=true;$('layersButton').setAttribute('aria-expanded','false');closeDetail();}});
document.addEventListener('click',e=>{const route=e.target.closest('[data-route]'),stop=e.target.closest('[data-stop]'),near=e.target.closest('[data-near-stop]'),exp=e.target.closest('[data-export]');if(route)selectRoute(route.dataset.route);if(stop)selectStop(stop.dataset.stop);if(near){const s=state.stops.find(s=>s.id===near.dataset.nearStop);if(s)setPoint(s.coord);}if(e.target.closest('[data-close]'))closeDetail();if(exp){const r=state.routes.find(r=>r.id===exp.dataset.export);if(!r)return;const url=URL.createObjectURL(new Blob([JSON.stringify({type:'FeatureCollection',features:[r.feature]},null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download='calais-ligne-'+r.short.replace(/[^a-zA-Z0-9_-]/g,'-')+'.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Le tracé de la ligne '+r.short+' a été exporté.');}});
async function init(){try{const [stopsData,routesData]=await Promise.all(['arrets','lignes'].map(async n=>{const res=await fetch('data/'+n+'.geojson');if(!res.ok)throw Error('Données indisponibles');return res.json();}));state.stops=stopsData.features.map((f,i)=>({id:f.properties.stop_id||String(i),name:f.properties.stop_name||'Arrêt sans nom',code:f.properties.stop_code,access:String(f.properties.wheelchair_boarding??'0'),coord:f.geometry.coordinates,feature:f}));state.routes=routesData.features.map(f=>{const p=f.properties,color=/^#[\da-f]{6}$/i.test(p.route_color)?p.route_color:'#087f73';const hex=color.slice(1),rgb=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16));return {id:p.route_id,short:p.route_short_name,name:p.route_long_name,color,textColor:(.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2])>150?'#102f39':'#fff',regular:/^\d+$/.test(p.route_short_name)||p.route_short_name==='B',lines:f.geometry.coordinates,bounds:Geo.bounds(f.geometry.coordinates),length:Geo.length(f.geometry.coordinates),feature:f};}).sort((a,b)=>a.short.localeCompare(b.short,'fr',{numeric:true}));state.ready=true;if(width<500)state.zoom=12;renderResults();updateStatus();schedule();registerTools();}catch(error){$('results').innerHTML='<div class="error-panel">Le réseau n’a pas pu être chargé. Vérifiez votre connexion et rechargez la page.<br><button class="btn outline" id="retry">Réessayer</button></div>';$('retry').onclick=init;$('mapStatus').textContent='Données indisponibles';}}
function registerTools(){if(!document.modelContext?.registerTool)return;const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});const tools=[{name:'search_calais_network',title:'Rechercher dans le réseau de Calais',description:'Recherche les noms des arrêts et des lignes et met à jour les résultats visibles.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.query!=='string'||input.query.length>200)throw Error('Une recherche textuelle de moins de 200 caractères est requise.');switchTab('explore');state.search=input.query;$('searchInput').value=input.query;renderResults();const q=norm(input.query);return {stops:state.stops.filter(s=>norm(s.name+' '+s.code).includes(q)).slice(0,20).map(s=>({id:s.id,name:s.name})),routes:state.routes.filter(r=>norm(r.short+' '+r.name).includes(q)).map(r=>({id:r.id,name:r.name}))};}},{name:'select_calais_route',title:'Afficher une ligne de Calais',description:'Sélectionne une ligne par son identifiant et affiche son tracé et sa fiche.',inputSchema:{type:'object',properties:{routeId:{type:'string'}},required:['routeId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){const r=state.routes.find(r=>r.id===input?.routeId);if(!r)throw Error('Identifiant de ligne inconnu.');selectRoute(r.id);return {id:r.id,name:r.name,nearbyStopCandidates:routeStops(r).length};}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}}
init();
